config-sparse:
  modules:
    aiSwapper:
      config:
        menu:
          contents:
            suggested-value:
              abbot:
                - name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  control:
                    binks: true
                    speech: true
                    lines: true
                    portrait: true
                    aic: true
                    aiv: true
                    lord: true
                    startTroops: true
        defaultLanguage:
          contents:
            suggested-value: null
        ai:
          abbot:
            binks:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            speech:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            lines:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            portrait:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            aic:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            aiv:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            lord:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
            startTroops:
              contents:
                suggested-value:
                  name: Die Hand
                  root: ucp/plugins/Hand/resources/ai/Hand/
                  active: true
  plugins: {}
meta:
  version: 1.0.0
